# Ruta del directorio del codigo fuente
SRC_DIR = src

# Nombre del archivo principal de Python
MAIN = main

# Comando para ejecutar Python
PYTHON = python3

# Objetivo por defecto
all:
	$(PYTHON) $(SRC_DIR)/$(MAIN).py

.PHONY: all
